### ISSUE TITLE
Checking for 4 items in a row doesn't always work.

### ISSUE THREAD

**Issue by ingoandelhofs** [web-development-collection/invisible-4-in-a-row#4]
When selecting 4 connected tiles in the bottom row (last rows / last columns), you can make 4 in a row without winning the game.

![image](https://user-images.githubusercontent.com/42770346/95427737-4f707f00-0948-11eb-8c2e-0830193bb8f1.png)

**Comment by zurda** [comment]
Hi @IngoA-1848613  , really nice project, I'd love to get involved. 

Can I take this issue? I'm curious what's going on :)

Edit: I'm afraid I underestimated the scope of this ticket, and I won't have the capacity to complete the task after all. Apologies, but I would like to be un assigned from it please.

**Comment by ingoandelhofs** [comment]
Hi, sure you can check it out! I'll assign you for this issue!

**Comment by zurda** [comment]
Hi there @IngoA-1848613 , I took a look at this locally, but I'm not sure if I'm missing something. I'd love to double check that I understand the rules here. 
When I play this simple game, starting with the red user, I feel like the red should win, but it's the yellow who wins. 

Can you elaborate on how the winner is decided, so I know I'm not missing anything, please? 
![simple-game](https://user-images.githubusercontent.com/16784959/95684064-d5a9f100-0be6-11eb-9a89-79ca39612ae3.gif)

**Comment by ingoandelhofs** [comment]
Hi @zurda! Yeah, the first player that makes 4 in a row wins. So in this case the RED player should win!

**Comment by zurda** [comment]
Thanks @IngoA-1848613 ,  I'm afraid I underestimated the scope of this ticket, and I won't have the capacity to complete the task after all. Apologies, but I would like to be un assigned from it please.
